# Generated by Django 5.1.1 on 2024-09-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GLOFattributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
                ('totalarea', models.TextField()),
                ('meanwidth', models.TextField()),
                ('meanlength', models.TextField()),
                ('meanelevation', models.TextField()),
                ('meandepth', models.TextField()),
                ('maxelevation', models.TextField()),
                ('minelevation', models.TextField()),
            ],
        ),
    ]
