# Generated by Django 5.1.1 on 2024-09-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GLOFattributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=20)),
                ('totalarea', models.DecimalField(decimal_places=4, max_digits=20)),
                ('meanwidth', models.DecimalField(decimal_places=4, max_digits=20)),
                ('meanlength', models.DecimalField(decimal_places=4, max_digits=20)),
                ('meanelevation', models.DecimalField(decimal_places=4, max_digits=20)),
                ('meandepth', models.DecimalField(decimal_places=4, max_digits=20)),
                ('maxelevation', models.DecimalField(decimal_places=4, max_digits=20)),
                ('minelevation', models.DecimalField(decimal_places=4, max_digits=20)),
            ],
        ),
    ]
